export const designers = [
  {
    id: 0,
    name: '모두에게',
    classNumber: '0',
    englishName: '',
    email: '',
    instagram: '',
    behance: '',
    message: '',
    avatar: '',
    fields: [],
  },
  {
    id: 1,
    name: '강지은',
    classNumber: '2020111419',
    englishName: 'Kang Jieun',
    email: 'gxv1812@naver.com',
    instagram: '@zien____11',
    behance: '',
    message: '다들 정말 고생하셨습니다! 고생한 만큼 뜻깊은 결과물을 얻을 수 있는 시간이었어요.',
    avatar: '/avatar/강지은.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 2,
    name: '고경희',
    classNumber: '2020111421',
    englishName: 'Go Gyeonghui',
    email: 'gogang123456@gmail.com',
    instagram: '@hu.iiiz',
    behance: '',
    message: '함께 만든 추억과 배움이 앞으로의 여정에 빛이 되길 바랍니다.',
    avatar: '/avatar/고경희.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 3,
    name: '고은지',
    classNumber: '2020111423',
    englishName: 'Ko Eunji',
    email: 'yjgoh01@gmail.com',
    instagram: '',
    behance: 'Eunji Ko',
    message:
      '많은 것을 배웠던 시간이었습니다. 다들 정말 수고 많으셨습니다! 학우분들이 뒤 이어 나아갈 길을 늘 응원합니다.',
    avatar: '/avatar/고은지.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 4,
    name: '공성연',
    classNumber: '2020111233',
    englishName: 'Kong Sungyun',
    email: 'yellow116@naver.com',
    instagram: '',
    behance: '',
    message: '모두들 너무 고생 많으셨습니다! 앞으로도 다들 좋은 일만 있으시길 바래요!',
    avatar: '/avatar/공성연.webp',
    fields: ['UX'],
  },
  {
    id: 5,
    name: '김소은',
    classNumber: '2019111419',
    englishName: 'Kim Soeun',
    email: 'soeun7736@naver.com',
    instagram: '',
    behance: '',
    message: '모두의 앞으로를 응원합니다.',
    avatar: '/avatar/19김소은.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 6,
    name: '김소은',
    classNumber: '2020111505',
    englishName: 'Kim Soeun',
    email: 'ssoaga9999@gmail.com',
    instagram: '@ssoeunee',
    behance: '',
    message:
      '내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라. 모두들 감사합니다, 응원합니다!',
    avatar: '/avatar/20김소은.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 7,
    name: '김유진',
    classNumber: '2020111425',
    englishName: 'Kim Eugene',
    email: 'bountifulastar@gmail.com',
    instagram: '@eunuhang',
    behance: '',
    message: '사~랑해요~',
    avatar: '/avatar/김유진.webp',
    fields: ['UX', 'BX'],
  },
  {
    id: 8,
    name: '김지현',
    classNumber: '2021111430',
    englishName: 'Kim Jihyeon',
    email: 'kant701223@gmail.com',
    instagram: '@jii.hyeon_208',
    behance: '',
    message:
      '좋은 분들과 함께할 수 있어서 뜻 깊은 시간이었고 함께한 모든 분들께 감사함을 전합니다. 앞으로의 길을 응원합니다!',
    avatar: '/avatar/김지현.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 9,
    name: '김채원',
    classNumber: '2020111427',
    englishName: 'Kim Chaewon',
    email: 'chaewon0125@naver.com',
    instagram: '@woni125',
    behance: '',
    message: '모두 수고 많으셨습니다! 앞으로를 응원합니다:)',
    avatar: '/avatar/김채원.webp',
    fields: ['UX', 'BX'],
  },
  {
    id: 10,
    name: '문가희',
    classNumber: '2020111431',
    englishName: 'Moon Gahui',
    email: 'ansrkgml56@naver.com',
    instagram: '@moooooooooongh',
    behance: '',
    message: '힘들고 재밌었습니다 다들 행복하세요><',
    avatar: '/avatar/문가희.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 11,
    name: '박수연',
    classNumber: '2020111434',
    englishName: 'Park Suyeon',
    email: 'sooyoun001@naver.com',
    instagram: '@seon._.o2',
    behance: 'Suyeon Park',
    message: '함께 마무리할 수 있어서 감사했습니다. 새로운 시작도 응원합니다!',
    avatar: '/avatar/박수연.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 12,
    name: '박은아',
    classNumber: '2020111435',
    englishName: 'Park Eun-a',
    email: 'unxxa01@gmail.com',
    instagram: '@_unxxa',
    behance: '',
    message: '지금껏 잘해왔 듯, 새롭게 시작하는 모두의 앞날을 응원합니다!',
    avatar: '/avatar/박은아.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 13,
    name: '박이은',
    classNumber: '2021120105',
    englishName: 'Park Lee-eun',
    email: 'peu11118@naver.com',
    instagram: '@2eun2silver',
    behance: 'Lee eun Park',
    message: '반짝이는 가치를 지닌 °˖✧◝(⁰▿⁰)◜✧˖° 디자이너로서의 시작을 응원합니다. ୧(˙Ⱉ˙)୨',
    avatar: '/avatar/박이은.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 14,
    name: '박인애',
    classNumber: '2020111436',
    englishName: 'Park In-ae',
    email: 'ab0574@naver.com',
    instagram: '@evol__ni_01',
    behance: '',
    message: 'Anyone can be anything! 여러분의 꿈을 응원합니다 :)',
    avatar: '/avatar/박인애.webp',
    fields: ['UX', 'BX'],
  },
  {
    id: 15,
    name: '반유진',
    classNumber: '2021111438',
    englishName: 'Yujin Yoonban',
    email: 'yujinyoonban@gmail.com',
    instagram: '@bban__12',
    behance: '',
    message: '언젠가 좋은 기회로 만나면 좋겠습니다.',
    avatar: '/avatar/반유진.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 16,
    name: '송의진',
    classNumber: '2019111266',
    englishName: 'Song Euijin',
    email: 'uijin2236@gmail.com',
    instagram: '@thmuttby',
    behance: '',
    message:
      '긴 프로젝트 함께 고생하느라 수고하셨습니다! 모두의 앞길이 빛나길 응원합니다. ദ്ദി・ᴗ・)✧',
    avatar: '/avatar/송의진.webp',
    fields: ['UX'],
  },
  {
    id: 17,
    name: '신주은',
    classNumber: '2020111438',
    englishName: 'Shin Jueun',
    email: 'juni0374@gmail.com',
    instagram: '@silver_s.j',
    behance: 'Juni Shin',
    message: '최선을 다했습니다. I did my best :-)',
    avatar: '/avatar/신주은.webp',
    fields: ['UX'],
  },
  {
    id: 18,
    name: '오유진',
    classNumber: '2020111440',
    englishName: 'Oh Yujin',
    email: '5yujin1027@gmail.com',
    instagram: '@yujin01_cs',
    behance: '',
    message: '도비는 자유예요 !',
    avatar: '/avatar/오유진.webp',
    fields: ['UX', 'BX'],
  },
  {
    id: 19,
    name: '우규리',
    classNumber: '2020111442',
    englishName: 'Woo Kyuri',
    email: 'le01032@naver.com',
    instagram: '@8ightooo',
    behance: 'Kyuri Woo',
    message: '모두에게 더 많은 행복과 행운이 오기를!',
    avatar: '/avatar/우규리.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 20,
    name: '유주하',
    classNumber: '2021111443',
    englishName: 'Lyu Juha',
    email: 'juhaebbi@naver.com',
    instagram: '@juhaebb',
    behance: '',
    message: '가장 설레는 새로운 시작이 기다리고 있습니다, 모두 응원합니다!',
    avatar: '/avatar/유주하.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 21,
    name: '윤주하',
    classNumber: '2018111439',
    englishName: 'Yoon Juha',
    email: 'ijooha16@gmail.com',
    instagram: 'ijooha',
    behance: '',
    message: '모든 선택을 응원합니다',
    avatar: '/avatar/윤주하.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 22,
    name: '이가연',
    classNumber: '2020111444',
    englishName: 'Lee Gayeon',
    email: 'lky070@naveer.com',
    instagram: '@gayeon._le',
    behance: 'lee gayeon',
    message: '우리의 모든 순간을 응원합니다 :-)',
    avatar: '/avatar/이가연.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 23,
    name: '이서영',
    classNumber: '2020111445',
    englishName: 'Lee Seoyoung',
    email: 'jksy0427@naver.com',
    instagram: '@namkoongseoyoung',
    behance: '',
    message: '졸업・ 야호♪───Ｏ（≧∇≦）Ｏ────♪',
    avatar: '/avatar/이서영.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 24,
    name: '이소연',
    classNumber: '2020111446',
    englishName: 'Lee Soyeon',
    email: 'soyeon6669@gmail.com',
    instagram: '@bllack_so',
    behance: 'soyeon LEE',
    message: '새로운 시작, 새로운 출발을 응원합니다:)',
    avatar: '/avatar/이소연.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 25,
    name: '이수현',
    classNumber: '2018110956',
    englishName: 'Lee Suhyeon',
    email: 'isuhyeon99@gmail.com',
    instagram: '',
    behance: '',
    message: '우리의 경험들을 빛내어 더 멋진 미래로 나아갑시다',
    avatar: '/avatar/이수현.webp',
    fields: ['BX'],
  },
  {
    id: 26,
    name: '이지은',
    classNumber: '2020111448',
    englishName: 'Lee Jieun',
    email: 'heheyaho@gmail.com',
    instagram: '@jijiiieu',
    behance: '',
    message: '모두 고생 많으셨습니다, 앞으로 모든 일이 잘 풀리기를 기원합니다',
    avatar: '/avatar/48이지은.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 27,
    name: '이지은',
    classNumber: '2020111447',
    englishName: 'Lee Jieun',
    email: 'leejieun8810@naver.com',
    instagram: 'ijieun2868',
    behance: '',
    message: '다들 열심히 마무리 지었습니다. 앞으로 닿는 모든 발걸음 응원합니다:)',
    avatar: '/avatar/47이지은.webp',
    fields: ['UX', 'BX'],
  },
  {
    id: 28,
    name: '이혜인',
    classNumber: '2020111449',
    englishName: 'Lee Hyein',
    email: 'UvioletU@gmail.com',
    instagram: '',
    behance: '',
    message: '모두의 앞날에 꽃길만 가득하길 응원하겠습니다',
    avatar: '/avatar/이혜인.webp',
    fields: ['UX'],
  },
  {
    id: 29,
    name: '장윤서',
    classNumber: '2021111447',
    englishName: 'Jang Yoonseo',
    email: 'jys09142000@naver.com',
    instagram: '@_yoonseo00_',
    behance: 'Yoonseo Jang',
    message: '새로운 시작을 응원합니다 !',
    avatar: '/avatar/장윤서.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 30,
    name: '전예지',
    classNumber: '2021120106',
    englishName: 'Jeon Yeji',
    email: 'jyeji99@naver.com',
    instagram: '@zebra486',
    behance: '',
    message: '짧은 시간 다들 고생 많으셨습니다 :) 모두의 꿈을 응원합니다!',
    avatar: '/avatar/전예지.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 31,
    name: '정가윤',
    classNumber: '2021111448',
    englishName: 'Jung Gayoon',
    email: 'rkdbs9@naver.com',
    instagram: '@g_yx.ni',
    behance: '',
    message: '모두 감사합니다! 수고하셨습니다:)',
    avatar: '/avatar/정가윤.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 32,
    name: '정다은',
    classNumber: '2021111449',
    englishName: 'Jung Daeun',
    email: 'wjdrkdms40@gmail.com',
    instagram: '@daani_0y',
    behance: '',
    message: '새로운 시작을 축하하며, 앞으로의 모든 여정이 행복으로 가득하길 기원합니다!',
    avatar: '/avatar/정다은.webp',
    fields: ['UX', 'BX'],
  },
  {
    id: 33,
    name: '정예승',
    classNumber: '2020111526',
    englishName: 'Jung Yeseung',
    email: 'yeseong01@naver.com',
    instagram: '@yelaree',
    behance: '',
    message: '헤매는만큼 내 땅이야!',
    avatar: '/avatar/정예승.webp',
    fields: ['UX', 'BX'],
  },
  {
    id: 34,
    name: '조수민',
    classNumber: '2020111454',
    englishName: 'Cho Sumin',
    email: 'csm3050914@naver.com',
    instagram: '@fre_e_sia_',
    behance: '',
    message:
      '함께해서 진심으로 행복했습니다( • ᴗ - )🤍!!! 매일이 행복으로 가득하기를 바라며 앞으로 더 빛날 미래를 응원합니다 ₊*｡⁺✩',
    avatar: '/avatar/조수민.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 35,
    name: '조수빈',
    classNumber: '2020111455',
    englishName: 'Cho Soobin',
    email: 'josubin0012@gmail.com',
    instagram: '@2odawn',
    behance: 'Soobin Cho',
    message: '앞으로 새로운 페이지를 써 내려갈 모든 여정을 응원합니다!',
    avatar: '/avatar/조수빈.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 36,
    name: '지예성',
    classNumber: '2021111450',
    englishName: 'Chee Yeseong',
    email: 'jiys0201@naver.com',
    instagram: '@ji_yecastle',
    behance: '',
    message: '하고싶은 일을 하며 살아가기를 기도합니다 :)',
    avatar: '/avatar/지예성.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 37,
    name: '천유정',
    classNumber: '2019111455',
    englishName: 'Chun Yujeong',
    email: 'dbrica5@gmail.com',
    instagram: '@yujzel',
    behance: '',
    message:
      '여러분들과 함께 멋진 마무리를 할 수 있어 즐거웠습니다. 모두들 원하시는 바 이루시도록 응원하겠습니다!',
    avatar: '/avatar/천유정.webp',
    fields: ['UX'],
  },
  {
    id: 38,
    name: '허찬비',
    classNumber: '2019111457',
    englishName: 'Heo Chanbi',
    email: 'socheolee@gmail.com',
    instagram: '',
    behance: '',
    message: '다들 정말 고생 많으셨습니다. 앞으로의 여정에서도 운과 행복이 함께하길 바랍니다. ^_^',
    avatar: '/avatar/허찬비.webp',
    fields: ['BX'],
  },
  {
    id: 39,
    name: '홍수정',
    classNumber: '2020111458',
    englishName: 'Hong Sujung',
    email: 'tn0wjd0@naver.com',
    instagram: '@floodaffection',
    behance: 'SUJUNG HONG',
    message: '먹고싶은게 많아서 꿈도 너무 많아! 뭐가됐든 행복하면 됐지⋆｡𖦹°˚ ༘⋆｡˚⊹',
    avatar: '/avatar/홍수정.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 40,
    name: '황예린',
    classNumber: '2021111456',
    englishName: 'Hwang Yerin',
    email: 'rinni.0128@gmail.com',
    instagram: '@yeeaa_rin',
    behance: '',
    message:
      '너무 고생하셨고 덕분에 행복했습니다! 서로의 꿈을 응원하며, 앞으로 행복만 가득하기를 기도하겠습니다 :) ',
    avatar: '/avatar/황예린.webp',
    fields: ['UX', 'DF'],
  },
  {
    id: 41,
    name: '황자경',
    classNumber: '2020111460',
    englishName: 'Hwang Jagyung',
    email: 'jagyeonghwang@gmail.com',
    instagram: '',
    behance: '',
    message: '새롭게 도전할 우리의 그 모든 순간들을 응원합니다 :)',
    avatar: '/avatar/황자경.webp',
    fields: ['UX'],
  },
] as const
